name: Build and Release Bundles

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Make create_bundles.sh executable
        run: chmod +x ./create_bundles.sh
      
      - name: Run bundle creation script
        run: ./create_bundles.sh
      
      - name: Upload bundle files to release
        uses: softprops/action-gh-release@v2
        with:
          files: ./*.bbsflmt
